# Generated by Django 2.2.5 on 2019-09-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix_up', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorproject',
            name='contractor_after_picture',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
