# Generated by Django 2.2.5 on 2019-09-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix_up', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorproject',
            name='seen',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
