# Generated by Django 2.2.5 on 2019-09-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix_up', '0002_auto_20190907_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorproject',
            name='contractor_after_picture',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contractorproject',
            name='contractor_before_picture',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
